#!/bin/bash

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Time
arch-chroot /mnt /bin/bash -c "
	locale-gen &&
	ln -sf /usr/share/zoneinfo/Europe/Copenhagen && 
	hwclock --systohc
"

# Localization
arch-chroot /mnt /bin/bash -c "
	echo 'LANG=en_US.UTF-8' > /etc/locale.conf &&
	echo 'KEYMAP=dk-latin1' > /etc/vconsole.conf
"

arch-chroot /mnt /bin/bash -c "echo 'arch-box' > /etc/hostname"

echo "Set root password to continue!"
arch-chroot /mnt /bin/bash -c 'passwd' # prompt for root password
